name: opsseer
services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml","--storage.tsdb.retention.time=2d"]
    volumes:
      - ./ops/prometheus:/etc/prometheus:ro
    ports:
      - "9090:9090"
    networks: [ops]

  grafana:
    image: grafana/grafana:10.4.6
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./ops/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on: [prometheus]
    networks: [ops]

  toyprod:
    build: { context: ./services/toyprod }
    container_name: toyprod
    environment:
      - FAIL_RATE=0
      - BASE_DELAY_MS=0
    ports:
      - "8000:8000"
    networks: [ops]

networks:
  ops:
    driver: bridge