# Use the official lightweight NGINX image
FROM nginx:stable-alpine

# Copy our static content into the default NGINX directory
COPY . /usr/share/nginx/html

# Expose port 80 for the web server
EXPOSE 80