apiVersion: 1
groups:
  - orgId: 1
    name: ToyProd Alerts
    folder: ToyProd
    interval: 1m
    rules:
      - uid: grafana-errorrate
        title: GrafanaErrorRateHigh
        condition: C
        for: 2m
        noDataState: NoData
        execErrState: Error
        labels:
          severity: page
        annotations:
          summary: "Grafana: error rate > 10% (5m)"
        data:
          - refId: A
            datasourceUid: prometheus
            relativeTimeRange: { from: 300, to: 0 }
            model:
              refId: A
              editorMode: code
              expr: toyprod:error_rate:ratio_5m
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: B
            datasourceUid: __expr__
            relativeTimeRange: { from: 300, to: 0 }
            model:
              refId: B
              type: threshold
              expression: 0.1
          - refId: C
            datasourceUid: __expr__
            relativeTimeRange: { from: 300, to: 0 }
            model:
              refId: C
              type: math
              expression: A > B