name: CI

on:
  push:
  pull_request:

jobs:
  validate-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Validate docker compose config
        run: docker compose -f docker-compose.yml config
